# Generated by Django 2.0 on 2017-09-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmap_app', '0002_auto_20170916_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=50, max_digits=50)),
                ('lon', models.DecimalField(decimal_places=50, max_digits=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MarkerOfInterest',
        ),
    ]
