# Generated by Django 2.0 on 2017-09-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gmap_app', '0003_auto_20170916_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='places',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='places',
            old_name='lon',
            new_name='longitude',
        ),
    ]
