# Generated by Django 2.0 on 2017-09-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmap_app', '0005_auto_20170917_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='latitude',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='places',
            name='longitude',
            field=models.CharField(default='', max_length=100),
        ),
    ]
